name: musify_clone
description: Simple YouTube Audio Player
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^2.5.3
  just_audio: ^0.9.46

flutter:
  uses-material-design: true
