name: musify_clone
description: Open source YouTube audio streaming app
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^2.0.0
  just_audio: ^0.9.36
  audio_service: ^0.18.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
